query StudentDisciplinesByClasses($input: StudentDisciplinesThroughClassesWithPaginationInput!) {
  studentDisciplinesThroughClassesWithPagination(input: $input) {
    page
    perPage
    total
    totalPages
    hasMore
    items {
      id
      name
      code
      studyHoursCount
      maxScore
      archivedAt
    }
  }
}

query GetStudentDiscipline($input: GetStudentDisciplineInput!) {
  getStudentDiscipline(input: $input) {
    discipline {
      id
      name
      code
      studyHoursCount
      maxScore
    }
    scoreForAnsweredTasks
    maxScoreForAnsweredTasks
    learningGroupId
    sectionId
    topics {
      topicId
      topic {
        id
        name
        order
        isCheckPoint
        maxScore
        studyHoursCount
      }
      status
      topicScore
    }
  }
}
